apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-deploy
  labels:
    app: sample-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sample-ctr
  template:
    metadata:
      labels:
        app: sample-ctr
    spec:
      containers:
      - name: sample-pod
        image: docker.io/raknas000/gameoflife-image:latest
        ports:
        - containerPort: 8080
           
